In [1]:
print('Lecture-22.ipynb')

Lecture-22.ipynb


### Python'da Matematiksel ve İstatistiksel Analiz

Numpy, SciPy, Pandas

python -m pip install numpy

pip install numpy

conda install numpy

https://numpy.org/doc/

Python'ın temel veri yapıları: Listeler, Demetler, Kümeler, Sözlükler Matematiksel ve İstatistiksel Analiz için çok uygun değillerdir. Vektörel işlemler, Numpy'da ndarray denilen vektörel işlemler yapabilen yeni bir veri yapısı oluşturulmş ve işlemlerde he pbu veri yapısı kullanılmıştır. built-in list

In [3]:
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
c = a + b
c

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [4]:
import numpy

In [6]:
x = numpy.array([1, 2, 3, 4, 5])
y = numpy.array([10, 20, 30, 40, 50])
z = x + y
z

array([11, 22, 33, 44, 55])

In [7]:
import numpy as np

### ndarray Veri Yapısı

ndarray vektörel bir dizi oluşturmak için kullanılan bir veri yapısıdır. ndarray

In [8]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))
# __str__

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
a = np.array((1, 2, 3, 4, 5))
print(a)

[1 2 3 4 5]


Numpy'daki türlere dtype deniliyor. her bir ndarray nesnesinin bir dtype türü vardır.

int
int8
int16
int32
int64
uint
uint8
uint16
uint32
float
float16
float32
float64
float128
complex
complex64
complex128
complex256

numpy dizilerinin her elemanı aynı dtype türünden olmak zorundadır. dtype tür isimlerindeki sayılar otürün bit uzunluğunu söyler. 

In [11]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a.dtype)
print(type(a.dtype))

int32
<class 'numpy.dtype[int32]'>


In [12]:
import numpy as np

a = np.array([1.2, 2.3, 3.4, 4.5, 5.6])
print(a.dtype)

float64


In [13]:
a = np.array([1, 2, 3.4, 4, 5.6])
print(a.dtype)

float64


In [14]:
a = np.array([1, 2, 3, 4, '5'])
a

array(['1', '2', '3', '4', '5'], dtype='<U11')

In [15]:
a.dtype

dtype('<U11')

In [16]:
a = np.array([1, 2, 3, 4, 5], dtype=np.float32)
a

array([1., 2., 3., 4., 5.], dtype=float32)

In [18]:
a = np.array([1, 2, 3, 4, 5], dtype='float32')
a

array([1., 2., 3., 4., 5.], dtype=float32)

In [19]:
a = np.array([[1, 2], [3, 4], [5,6]], dtype=np.int64)
a

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int64)

In [20]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [21]:
a.ndim

2

In [23]:
b = np.array([1, 2, 3, 4, 5])
b.ndim

1

In [24]:
b = np.array([1, 2, 3, 4, 5], ndmin=2)
print(b)

[[1 2 3 4 5]]


In [25]:
a = np.array(10)
a

array(10)

In [26]:
print(a)

10


In [27]:
type(a)

numpy.ndarray

In [28]:
a.ndim

0

In [29]:
a = np.array([[1, 2], [3,4], [5,6], [7,8]])
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [31]:
a.shape # 4 satır, 2 sütun

(4, 2)

### Ndarray nesnesi yaratan diğer fonksiyonlar

- array fonksiyonu
- zeros --> içi sıfır dolu bir ndarray nesnesi yaratıyor.

numpy.zeros(shape, dtype=float, order='C')

In [32]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
b = np.zeros((3,2))
b

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [35]:
c = np.zeros((10,))
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
a = np.zeros((3,3), dtype='float32')
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [37]:
# order: sütun temelli mi, satır temelli mi -> ?

In [38]:
# numpy.ones(shape, dtype=None, order='C')

a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [40]:
type(a.dtype)

numpy.dtype[float64]

In [42]:
#numpy.full(shape, fill_value, dtype=None, order='C')

a = np.full((4, 2), 5, dtype='int16')
a

array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5]], dtype=int16)

In [43]:
# numpy.diag(v, k=0)

a = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
b = np.diag(a)
b

array([1, 5, 9])

In [45]:
b = np.diag(a, 1)
b

array([2, 6])

In [46]:
b = np.diag(a, -1)
b

array([4, 8])

In [47]:
# numpy.arange([start, ]stop, [step, ]dtype=None)

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
b = np.arange(5, 10)
b

array([5, 6, 7, 8, 9])

In [49]:
c = np.arange(10, 20, 2)
c

array([10, 12, 14, 16, 18])

In [52]:
c = np.arange(20, 10, -1)
c

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [53]:
a = np.arange(5, 10.7, 0.5)
a

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ,
       10.5])

In [54]:
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

a = np.linspace(10, 20, 11)
a

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [55]:
b = np.linspace(10, 20, 22)
b

array([10.        , 10.47619048, 10.95238095, 11.42857143, 11.9047619 ,
       12.38095238, 12.85714286, 13.33333333, 13.80952381, 14.28571429,
       14.76190476, 15.23809524, 15.71428571, 16.19047619, 16.66666667,
       17.14285714, 17.61904762, 18.0952381 , 18.57142857, 19.04761905,
       19.52380952, 20.        ])

In [56]:
# numpy.empty(shape, dtype=float, order='C')

a = np.empty(10, dtype=np.int32)
a # garbage values

array([4128860, 6029375, 3801155, 5570652, 6619251, 7536754,       0,
             0,       0,       0])

In [60]:
# ndarray(shape, dtype=float, buffer=None, offset=0, strides=None, order=None) 

a = np.ndarray(10, dtype=np.int32)
a

array([617678000,       454,         0,       454,      1064,         0,
             768,       454, 698844208,       454])

In [62]:
# zeros_like, ones_like, full_like, empty_like 

a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [64]:
b = np.zeros_like(a, dtype=np.int32)
b

array([[0, 0],
       [0, 0],
       [0, 0]])

In [65]:
c = np.full_like(a, 100)
c

array([[100, 100],
       [100, 100],
       [100, 100]])

In [66]:
#numpy.identity(n, dtype=None)

a = np.identity(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [67]:
# eye

a = np.eye(5, k = +1)
a

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [68]:
a = np.eye(5, k = -2)
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

array
zeros
ones
diag
arange
linspace
full
empty
ndarray
zeros_like
ones_like
full_like
empty_like
identity
eye

## Numpy Dizilerinde İndeksleme ve Dilimleme

slicing

In [69]:
a = np.array(range(10, 110, 10))
a[5]

60

In [70]:
a[7]

80

In [71]:
# ndarray değiştirilebilir mutable bir sınıftır. 

a = np.array(range(10, 110, 10))
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [72]:
a[3] = 1000
a[7] = 5000
a

array([  10,   20,   30, 1000,   50,   60,   70, 5000,   90,  100])

In [73]:
a = np.array(range(10, 110, 10))
a[-1]

100

In [74]:
a[-2]

90

In [75]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
a[1, 2]

6

In [77]:
a[2, 2]

9

In [78]:
a[-1, 1]

8

In [79]:
a[-1, -1]

9

In [80]:
a = np.array(range(10, 110, 10))

b = a[3:5]
b

array([40, 50])

In [81]:
type(b)

numpy.ndarray

In [82]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
a[::2]

array([0, 2, 4, 6, 8])

In [84]:
a[::-2]

array([9, 7, 5, 3, 1])

In [85]:
a = np.array(range(10, 110, 10))
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [86]:
a[3:5] = [1000, 2000]
a

array([  10,   20,   30, 1000, 2000,   60,   70,   80,   90,  100])

In [87]:
a = np.array(range(10, 110, 10))
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [88]:
a [3:6] = [1000, 2000, 3000]
a

array([  10,   20,   30, 1000, 2000, 3000,   70,   80,   90,  100])

In [89]:
a[3:6] = [1000, 2000]

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [90]:
a = np.array([[1, 2, 3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
a[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [92]:
a[:2, 1:]

array([[2, 3],
       [5, 6]])

In [93]:
a[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [96]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [97]:
a = np.array([[1, 2, 3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
a[1, :]

array([4, 5, 6])

In [99]:
a = np.array([10, 20, 30, 40, 50])
a[1:4] = -1
a

array([10, -1, -1, -1, 50])

In [100]:
a = np.array([10, 20, 30, 40, 50])
a[1:4] = [1, 2, 3]
a


array([10,  1,  2,  3, 50])

In [101]:
a[1:4] = [1,2]

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [102]:
a = np.array([10, 20, 30, 40, 50])
a[1:4] = (1, 2, 3)
a

array([10,  1,  2,  3, 50])

In [107]:
a = np.array([[1, 2, 3], [4,5,6], [7,8,9]])
print(a)
a[2] # a[2, :]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([7, 8, 9])

In [110]:
a[, 2]

SyntaxError: invalid syntax (3556817452.py, line 1)

In [111]:
a[..., 2]

array([3, 6, 9])

In [112]:
a[:, 2]

array([3, 6, 9])

## Numpy: İndeksleme



In [113]:
a = np.array([10, 20, 30, 40, 50])
b = [2, 4, 1]
c = a[b]
a

array([10, 20, 30, 40, 50])

In [114]:
c

array([30, 50, 20])

In [116]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])
b = np.array([1, 3, 5])
a[b]

array([20, 40, 60])

In [117]:
b = (1, 3, 5)
a[b]

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [ ]:
# a[(x, y, z)] -> a[x, y, z]